TheRuffianPosseDjango/urls.py
from django.contrib import admin
from django.urls import path
from django.views.generic import TemplateView

from posse import views as posse_views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', posse_views.shadowlands_class_chart, name='home'),
    #path('', posse_views.home, name='home'),
    #path('', TemplateView.as_view(template_name='awareness.html'), name='home'),
    path('guild/', posse_views.home, name='home'),
    path('news/<int:id>/', posse_views.read_news, name='read_news'),
    path('apply', posse_views.apply_to_guild, name='apply_to_guild'),
    path('update_leadership', posse_views.update_guild_leadership, name='update_leadership'),
    path('leadership', posse_views.display_guild_leadership, name='display_guild_leadership'),
    path('shadowlands', posse_views.shadowlands_class_chart, name='shadowlands'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

posse/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.text import slugify


class GuildInformation(models.Model):
    guild_name = models.CharField(max_length=100)
    guild_name_slug = models.SlugField(blank=True, null=True)
    guild_main_realm = models.CharField(max_length=100)
    guild_main_realm_slug = models.SlugField(blank=True, null=True)
    guild_ranks_to_query = models.CharField(max_length=100)
    guild_description = models.TextField()

    class Meta:
        verbose_name_plural = 'Guild Information'

    def save(self, *args, **kwargs):
        self.guild_name_slug = slugify(self.guild_name)
        self.guild_main_realm_slug = slugify(self.guild_main_realm)
        super(GuildInformation, self).save(*args, **kwargs)

    def __str__(self):
        return self.guild_name


class BlizzardApiSettings(models.Model):
    client_key = models.CharField(max_length=200)
    client_secret = models.CharField(max_length=200)
    token_api_url = models.URLField()
    character_media_api_url = models.URLField()
    character_profile_api_url = models.URLField()
    guild_api_url = models.URLField()

    class Meta:
        verbose_name_plural = 'Blizzard API Settings'

    def __str__(self):
        return 'Blizzard API Settings'


class WarcraftLogsSettings(models.Model):
    days_to_show = models.IntegerField()
    api_url = models.URLField()

    class Meta:
        verbose_name_plural = 'WarcraftLogs Settings'

    def __str__(self):
        return 'WarcraftLogs Settings'


class RaiderIOSettings(models.Model):
    raid_rankings_api_url = models.URLField()
    raid_progression_api_url = models.URLField()

    class Meta:
        verbose_name_plural = 'Raider.IO Settings'

    def __str__(self):
        return 'Raider.IO Settings'


class GuildNews(models.Model):
    news_description = models.CharField(max_length=255)
    news_body = models.TextField()
    added_by = models.ForeignKey(User, on_delete=models.CASCADE)
    added_on = models.DateTimeField(auto_created=True)
    active = models.BooleanField(default=True)

    class Meta:
        verbose_name_plural = 'Guild News and Updates'

    def __str__(self):
        return self.news_description


class HelpfulGuildLinks(models.Model):
    link_name = models.CharField(max_length=255)
    link_url = models.URLField()
    link_active = models.BooleanField(default=True)

    class Meta:
        verbose_name_plural = 'Helpful Guild Links'

    def __str__(self):
        return self.link_name


class GuildAddonLinks(models.Model):
    addon_name = models.CharField(max_length=255)
    link_url = models.URLField()

    class Meta:
        verbose_name_plural = 'Guild Addon Links'

    def __str__(self):
        return self.addon_name


APPLICANT_CHOICES = [
    ('Pending', 'Pending'),
    ('Approved', 'Approved'),
    ('Denied', 'Denied'),
]


class GuildApplications(models.Model):
    character_armory_link = models.URLField()
    discord_username = models.CharField(max_length=100)
    character_image_url = models.URLField()
    character_name = models.CharField(max_length=12)
    character_realm = models.CharField(max_length=100)
    character_class = models.CharField(max_length=20)
    character_level = models.IntegerField()
    character_item_level_equipped = models.IntegerField()
    application_status = models.CharField(max_length=20, choices=APPLICANT_CHOICES, default=APPLICANT_CHOICES[0][0])

    class Meta:
        verbose_name_plural = 'Guild Applicants'
        unique_together = [['character_name', 'character_realm']]

    def __str__(self):
        return '{} => {} => {}'.format(self.character_name, self.discord_username, self.application_status)


class GuildLeadership(models.Model):
    character_name = models.CharField(max_length=12)
    character_image_url = models.URLField()
    guild_rank = models.IntegerField()
    character_realm = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = 'Guild Leaders'

    def __str__(self):
        return self.character_name


class GuildMOTD(models.Model):
    guild_motd_desc = models.CharField(max_length=255)
    guild_motd = models.TextField()
    posted_on = models.DateTimeField(auto_created=True)

    class Meta:
        verbose_name_plural = 'Guild Messages of the Day'

    def __str__(self):
        return self.guild_motd_desc


CLASS_CHOICES = [
    ('TANK_DK', 'Tank Death Knight'),
    ('DPS_DK', 'DPS Death Knight'),
    ('TANK_DH', 'Tank Demon Hunter'),
    ('DPS_DH', 'DPS Demon Hunter'),
    ('TANK_DRUID', 'Tank Druid'),
    ('DPS_DRUID', 'DPS Druid'),
    ('HEALER_DRUID', 'Healer Druid'),
    ('HUNTER', 'Hunter'),
    ('MAGE', 'Mage'),
    ('TANK_MONK', 'Tank Monk'),
    ('DPS_MONK', 'DPS Monk'),
    ('HEALER_MONK', 'Healer Monk'),
    ('TANK_PALADIN', 'Tank Paladin'),
    ('DPS_PALADIN', 'DPS Paladin'),
    ('HEALER_PALADIN', 'Healer Paladin'),
    ('HEALER_PRIEST', 'Healer Priest'),
    ('DPS_PRIEST', 'DPS Priest'),
    ('ROGUE', 'Rogue'),
    ('HEALER_SHAMAN', 'Healer Shaman'),
    ('DPS_SHAMAN', 'DPS Shaman'),
    ('WARLOCK', 'Warlock'),
    ('TANK_WARRIOR', 'Tank Warrior'),
    ('DPS_WARRIOR', 'DPS Warrior'),

]


class ShadowlandsClassChart(models.Model):
    username = models.CharField('Current Main Name', max_length=25)
    shadowlands_main = models.CharField('Shadowlands Main', max_length=50, choices=CLASS_CHOICES)
    shadowlands_main_alt = models.CharField('Shadowlands Main Alt', max_length=50, choices=CLASS_CHOICES, blank=True, null=True)

    class Meta:
        verbose_name_plural = 'Shadowlands Class Chart'
        unique_together = [['username', 'shadowlands_main']]

    def __str__(self):
        return self.username

templates/apply.html
{% extends 'base.html' %}
{% block title %} <title>The Ruffian Posse</title> {% endblock %}
{% block content %}
{% load posse_filters %}

    <form action="" method="post">
    {% csrf_token %}
    {{ form.as_table }}
    <input class="btn-warning" type="submit" value="Posse Up!">
    </form>

    <hr>
    {% if current_applicants %}
    <h3>Pending Recruits</h3>

    <div class="col-lg-7">
        <div class="container">
            {% for toon in current_applicants %}
            <div class="card" style="width:500px">
                <img class="card-img-top" src="{{toon.character_image_url}}" alt="Card image">
                <div class="card-img-overlay">
                    <h4 class="card-title">{{ toon.character_name|title }} of {{ toon.character_realm|title|replace_dashes }}</h4>
                    <p>Level : {{ toon.character_level }}</p>
                    <p>Item Level : {{ toon.character_item_level_equipped }}</p>
                    <a href="{{ toon.character_armory_link }}" class="btn btn-primary">See Profile</a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    {% endif %}

    {% if current_classes %}
    <h3>Shadowland Classes</h3>
        <h5>Main Alt can be blank</h5>

    <div class="col-lg-7">
        <div class="container">
        </table>
        <table class="table table-striped table-dark">
          <thead>
            <tr>
              <th scope="col">Current Main Name</th>
              <th scope="col">Shadowlands Main</th>
              <th scope="col">Shadowlands Main Alt</th>
            </tr>
          </thead>
          <tbody>
          {% for toon in current_classes %}
            <tr>
              <td>{{ toon.username }}</td>
              <td>{{ toon.get_shadowlands_main_display }}</td>
              <td>{{ toon.get_shadowlands_main_alt_display }}</td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
        </div>
    </div>
    <h3>Role Breakdown</h3>
    <div class="col-lg-7">
        <div class="container">
        </table>
        <table class="table table-striped table-dark">
          <thead>
            <tr>
              <th scope="col">Role</th>
              <th scope="col">Count</th>
            </tr>
          </thead>
          <tbody>
            <tr>
                <td>DPS</td>
                <td>{{ dps_count|length }}</td>
            </tr>
            <tr>
                <td>HEALERS</td>
                <td>{{ healer_count|length }}</td>
            </tr>
            <tr>
                <td>TANKS</td>
                <td>{{ tank_count|length }}</td>
            </tr>
          </tbody>
        </table>
        </div>
    </div>
    {% endif %}

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    {% block title %}<title>The Ruffian Posse</title>{% endblock %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Muli|Odibee+Sans|Rubik:500|Rubik&display=swap" rel="stylesheet">

</head>
<nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top">

  <!-- Links -->
  <ul class="navbar-nav">
    <li class="nav-item">
        <a class="nav-link" href="{% url 'home' %}">Home</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'shadowlands' %}">Shadowlands Class Selection</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'apply_to_guild' %}">Ride with the Posse</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'display_guild_leadership' %}">Guild Leadership</a>
    </li>
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
        Guild Addons
      </a>
      <div class="dropdown-menu">
          {% for link in addon_links %}
          <a class="dropdown-item" href="{{ link.link_url }}" target="_blank">{{ link.addon_name }}</a>
          {% endfor %}
      </div>
    </li>
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
        Important Guild Links
      </a>
      <div class="dropdown-menu">
          {% for link in helpful_links %}
          <a class="dropdown-item" href="{{ link.link_url }}" target="_blank">{{ link.link_name }}</a>
          {% endfor %}
      </div>
    </li>
  </ul>
</nav>

<body>
<div class="jumbotron">
    <h1 class="display-4"><a class="text-decoration-none" href="https://worldofwarcraft.com/en-us/guild/us/grizzly-hills/the-ruffian-posse" target="_blank">The Ruffian Posse</a></h1>
  <p class="lead">US | Alliance | Grizzly Hills / Lothar</p>
  <hr class="my-4">
  <p><h3>Havin' Fun and Gettin' Shit Done.</h3></p>
</div>
<div class=".bg-secondary">
    {% block content %}{% endblock %}
</div>
<div class="footer">
  <ul class="navbar-nav ml-auto">
    <li class="nav-item">
      <a class="nav-link" href="{% url 'admin:index' %}" target="_blank">Admin</a>
    </li>
  </ul>
</div>
</body>
</html>

templates/front_page.html
{% extends 'base.html' %}
{% block title %} <title>The Ruffian Posse</title> {% endblock %}
{% block content %}
{% load posse_filters %}

    <!--- Main Stuff --->

{% if guild_motd %}
    <div class="container-full">
        <div class="container">
            <div class="card text-white mb-4  mt-3 left border-light top">
              <div class="card-header">
                  <a class="text-decoration-none">Guild Message of the Day</a>
              </div>
              <div class="card-header">
                  <p class="text-muted"><small>{{ guild_motd.guild_motd_desc | title }} | {{ guild_motd.posted_on }}</small></p>
              </div>
              <div class="card-body">
                <p class="card-text ">{{ guild_motd.guild_motd | safe }}</p>
              </div>
            </div>
        </div>
    </div>
{% endif %}
    <div class="container-full">
        <div class="row">
            <div class="col-lg-6">
                <table border="2">
                <tr>
                    <th>Instance Name</th>
                    <th>Best Progress</th>
                    <th>Normal Kills</th>
                    <th>Heroic Kills</th>
                    <th>Mythic Kills</th>
                </tr>
                    {% for raid_name, raid_progression_info in guild_raid_progression.raid_progression.items %}
                    <tr>
                        <td>{{ raid_name|title|replace_dashes }}</td>
                            <td>{{ raid_progression_info.summary }}</td>
                            <td>{{ raid_progression_info.normal_bosses_killed }}</td>
                            <td>{{ raid_progression_info.heroic_bosses_killed }}</td>
                            <td>{{ raid_progression_info.mythic_bosses_killed }}</td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
            <div class="col-lg-6">
                <table border="2">
                    {% for raid_name, raid_ranking_info in guild_raid_rankings.raid_rankings.items %}
                    <tr>
                        <th colspan="3">{{ raid_name|title|replace_dashes }}</th>
                        {% for difficulty, nested_value in raid_ranking_info.items %}
                            <td>{{ difficulty|title }}: {% if nested_value.realm == 0 %}No Kills{% else %}{{ nested_value.realm }}{% endif %}</td>
                        {% endfor %}
                    </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
<div class="container-full">
  <div class="row">
    <div class="col-lg-7">
        <div class="container">
            {% for news in guild_news %}
            <div class="card text-white mb-4  mt-3 left border-light top">
              <div class="card-header">
                  <a class="text-decoration-none" href="{% url 'read_news' news.id %}">{{ news.news_description }}</a>
              </div>
              <div class="card-header">
                  <p class="text-muted"><small>{{ news.added_by | title }} | {{ news.added_on }}</small></p>
              </div>
              <div class="card-body">
                <p class="card-text ">{{ news.news_body | safe | truncatewords:50 }}</p>
              </div>
            </div>
            {% endfor %}
        </div>
    </div>
  <!--- raid progression --->
    <div class="col-lg-5">
        <table border="2">
            <tr>
                <th colspan="4">Recent Raid Logs</th>
            </tr>
            <tr>
                <th>Title</th>
                <th>Date</th>
                <th>Zone</th>
                <th>Links</th>
            </tr>
            {% for item in warcraft_logs %}
                <tr>
                    <td>{{ item.title }}</td>
                    <td>{{ item.start | ctime }}</td>
                    <td>{{ item.zone | translate_zone_number }}
                    <td><a href="https://www.warcraftlogs.com/reports/{{ item.id }}" target="_blank"><img width="16" height="16" src="https://dmszsuqyoe6y6.cloudfront.net/img/warcraft/favicon.png"></a> <a href="https://www.wipefest.net/report/{{ item.id }}" target="_blank"><img src="https://www.wipefest.gg/favicon.ico"></a> <a href="https://www.wowanalyzer.com/report/{{ item.id }}" target="_blank"><img src="https://wowanalyzer.com/favicon.ico"></a></td>
                </tr>
            {% endfor %}
        </table>
    </div>
  </div>
</div>

{#    <div class="container-full">#}
{#        <div class="row">#}
{#            <div class="col-lg-7">#}
{#                <iframe src="https://discordapp.com/widget?id=295363255117938688&theme=dark&username=Kalinakov#7485" width="600" height="500" allowtransparency="true" frameborder="0"></iframe>#}
{#            </div>#}
{#        </div>#}
{#    </div>#}

    <!--- END Main Stuff --->
{% endblock %}

templates/leadership.html
{% extends 'base.html' %}
{% block title %} <title>The Ruffian Posse</title> {% endblock %}
{% block content %}
{% load posse_filters %}

<p>{{ guild_info.guild_name }}</p>
<p>{{ guild_info.guild_main_realm }}</p>
<p>{{ guild_info.guild_description }}</p>


{% regroup my_guild_leaders|dictsort:"guild_rank" by guild_rank as ranked_list %}

	{% for rank in ranked_list %}
        <div class="col-lg-7">
            <div class="container">
                {% for member_rank in rank.list %}
                <div class="card w-20" style="width:500px">
                    <img class="card-img-top" src="{{member_rank.character_image_url}}" alt="Card image">
                    <div class="card-img-overlay">
                        <h4 class="card-title">{{ member_rank.character_name|title }} of {{ member_rank.character_realm|title|replace_dashes }}</h4>
                        <p>{{ member_rank.guild_rank|translate_guild_rank }}</p>
                        <a href="https://worldofwarcraft.com/en-us/character/us/{{ member_rank.character_realm }}/{{ member_rank.character_name }}" target="_blank" class="btn btn-primary">See Profile</a>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        {% if rank.grouper == 1 %}
            <hr>
        {% endif %}
	{% endfor %}



{% endblock %}

templates/oops.html
{% extends 'base.html' %}
{% block title %} <title>The Ruffian Posse</title> {% endblock %}
{% block content %}
{% load posse_filters %}

    <div class="col-lg-7">
        <div class="container">
            <div class="card" style="width:500px">
                <img class="card-img-top" src="https://40.media.tumblr.com/c312cc39bc83b8a81c0820fcd399341c/tumblr_nq44kpcfF51qjo5ngo1_1280.png" alt="Card image">
                <div class="card-img-overlay">
                    <h4 class="card-title">Oops!</h4>
                    <p>{{ message }}</p>
                </div>
        </div>
    </div>

{% endblock %}

templates/read_news.html
{% extends 'base.html' %}
{% block title %} <title>The Ruffian Posse</title> {% endblock %}
{% block content %}
{% load posse_filters %}


    <!--- Random Junk --->
<div class="container-full">
    <div class="col-lg-12">
        <div class="row">
            <div class="card-body">
                <h1>{{ news_post.news_description }}</h1>
                <p class=" text-muted">{{ news_post.added_by | title }} | {{ news_post.added_on }}</p>
                <p class="card-text ">{{ news_post.news_body | safe }}</p>
            </div>
        </div>
    </div>
</div>

    <!--- END Random Junk --->
{% endblock %}